### ISSUE TITLE
Setting 'max_len_single_sentence' is now deprecated. This value is automatically set up.

### ISSUE THREAD

**Issue by bhadreshpsavani** [microsoft/MPNet#10]
When running the Training script for SQUAD I was getting the below error.
```
Traceback (most recent call last):
  File "/media/data2/anaconda/envs/mpnet/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/media/data1/bhadresh/MPNet/MPNet/pretraining/fairseq_cli/train.py", line 370, in cli_main
    main(args)
  File "/media/data1/bhadresh/MPNet/MPNet/pretraining/fairseq_cli/train.py", line 47, in main
    task = tasks.setup_task(args)
  File "/media/data1/bhadresh/MPNet/MPNet/pretraining/fairseq/tasks/__init__.py", line 17, in setup_task
    return TASK_REGISTRY[args.task].setup_task(args, **kwargs)
  File "/media/data1/bhadresh/MPNet/MPNet/pretraining/fairseq/tasks/squad2.py", line 104, in setup_task
    return cls(args, dictionary)
  File "/media/data1/bhadresh/MPNet/MPNet/pretraining/fairseq/tasks/squad2.py", line 84, in __init__
    self.tokenizer = SQuADTokenizer(args.bpe_vocab_file, dictionary)
  File "/media/data1/bhadresh/MPNet/MPNet/pretraining/fairseq/tasks/squad2.py", line 42, in __init__
    self.max_len_single_sentence = self.max_len - 2
  File "/media/data2/anaconda/envs/mpnet/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1547, in max_len_single_sentence
    raise ValueError(
ValueError: Setting 'max_len_single_sentence' is now deprecated. This value is automatically set up.
```

By commenting out line 42 and 43 in [file](https://github.com/microsoft/MPNet/blob/master/pretraining/fairseq/tasks/squad2.py)
```
 self.max_len_single_sentence = self.max_len - 2
 self.max_len_sentences_pair = self.max_len - 3
```
It resolves but is it fine to do so?

When I run the script, I was getting less F1 score and Exact Match than mentioned in the Paper. I also created an [issue ](https://github.com/microsoft/MPNet/issues/9) for that

**Comment by StillKeepTry** [comment]
You can try [this version](https://github.com/StillKeepTry/transformers/blob/master/src/transformers/modeling_mpnet.py) for fine-tuning
